Kinesis channel performance test report
triggermesh/test-infra pull request #119
Opened 2021-11-12 15:16 UTC by tzununbekov

I had to re-run tests since I expected to see the difference between GKE->AWS and EKS->AWS test environments.
[Rendered doc](https://github.com/triggermesh/test-infra/tree/kinesis-channel-report/perf/reports/20210215-kinesis-channel)

2021-11-15 00:37 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +With the steam rate of 600 events per second channel could successfully handle 84.33% of events for 6 minutes before dispatcher timeouts exceeded the receiver's wait period.
```suggestion
With the stream rate of 600 events per second channel could successfully handle 84.33% of events for 6 minutes before dispatcher timeouts exceeded the receiver's wait period. 
```

2021-11-15 00:37 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +In the first two tests Kinesis channel successfully sustained throughput of 300 and 500 events per second for 10 minutes with average latency around 10ms.
```suggestion
In the first two tests, the Kinesis channel successfully sustained throughput of 300 and 500 events per second for 10 minutes with average latency around 10ms.
```

2021-11-15 00:38 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +Monitoring data showed that the most probable reason for observed behavior is suboptimal memory management in the Kinesis channel dispatcher. Resources other than RAM had linear graphs with no spikes
These first three tests are representing data ingesting into the stream and data reads from the stream to get to the receiver, correct ?

2021-11-15 00:44 UTC, sebgoa commented
Thanks for this Timur.

I do like the final recommendation but we should definitely investigate further to understand why we are far from the 3,000 events/sec that 3 shards could ingest.

Can you follow up with an issue in the kinesis channel repo ?

thanks

2021-11-15 00:45 UTC, sebgoa requested changes

2021-11-15 00:45 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +For sustained loading tests, we used [cegen](../../tools/cegen/) to generate CloudEvents with a fixed size of 2KiB, piped to `vegeta` attacker configured to send these events to a receiver. We ran mu
I would like to see a basic test of ingesting data into the stream using vegeta in order to verify that we can ingest at around 3,000 events/sec into the stream.

2021-11-15 00:45 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +AWS Kinesis channel that was used during the tests had 3 shards which in total should be capable of up to 3 MB/sec (or 3000 records/sec) of "put" operations and up to 30 MB/sec (or 30000 records/sec)
to remove the "should" in this first sentence we need to run an ingesting test alone.

2021-11-15 00:45 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +with a payload of 2 KiB. AWS Kinesis stream backed the channel was configured with different numbers of shards for the same test sets. In general, the channel performance was not affected by the numb
```suggestion
with a payload of 2 KiB. The AWS Kinesis stream backing the channel was configured with different numbers of shards for the same test sets. In general, the channel performance was not affected by the number of the shards as the limiting factor is the dispatching process.
```

2021-11-15 00:45 UTC, sebgoa commented on perf/reports/20210215-kinesis-channel/README.md
> +In a conclusion, we recommend limiting event flow through the Kinesis channel to 500 events/sec until further improvements are made to the dispatcher controller.
```suggestion
In a conclusion, we recommend limiting the event flow through the Kinesis channel to 500 events/sec until further improvements are made to the dispatcher controller.
```

2021-11-15 07:58 UTC, tzununbekov commented on perf/reports/20210215-kinesis-channel/README.md
> +Monitoring data showed that the most probable reason for observed behavior is suboptimal memory management in the Kinesis channel dispatcher. Resources other than RAM had linear graphs with no spikes
These numbers are about ingesting events into the Kinesis stream. The receiver end report graph shows the number of received events per second and it is very dispersed: 
![chart](https://user-images.githubusercontent.com/13515865/141742992-e8d35c70-74ec-4437-add3-919a63e085df.png)

I'll include these graphs in the update.

2021-11-15 07:58 UTC, tzununbekov commented on perf/reports/20210215-kinesis-channel/README.md
> +AWS Kinesis channel that was used during the tests had 3 shards which in total should be capable of up to 3 MB/sec (or 3000 records/sec) of "put" operations and up to 30 MB/sec (or 30000 records/sec)
will do

2021-11-15 20:53 UTC, tzununbekov commented
@sebgoa I added a couple of fixes to the controller, re-run tests, and updated the report. Please take another look

2021-11-23 09:05 UTC, sebgoa commented
thanks for the improvements, happy to see we can reach the shard limits.

2021-11-23 09:05 UTC, sebgoa approved these changes

2021-11-23 09:07 UTC, merged